package sol3675.middleearththaumaturgy;

import cpw.mods.fml.common.ModMetadata;
import sol3675.middleearththaumaturgy.references.LibMisc;

public class ModInfo {
	public static void loadInfo(ModMetadata meta)
	{
		meta.modId = LibMisc.MODID;
		meta.name = LibMisc.MODNAME;
		meta.description = "Middle-Earth Thaumaturgy is an addon to add LotR themed things to Thaumcraft.";
		meta.version = LibMisc.VERSION;
		meta.url = "";
		meta.updateUrl = "";
		meta.authorList.add("Coding: SOL3675");
		meta.authorList.add("Artists: SOL3675, Rei Rokusanami, GUNSOU, Hosta Plantain");
		meta.credits = "";
		meta.logoFile = "assets/middleearththaumaturgy/logo.png";
		meta.autogenerated = false;
	}
}
